### ISSUE TITLE
Sometime getting this error in client

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash-client-java#108]
Caused by: java.lang.NullPointerException: null
	at no.finn.unleash.metric.MetricsBucket.registerCount(MetricsBucket.java:19)
	at no.finn.unleash.metric.UnleashMetricServiceImpl.count(UnleashMetricServiceImpl.java:43)
	at no.finn.unleash.DefaultUnleash.count(DefaultUnleash.java:138)
	at no.finn.unleash.DefaultUnleash.isEnabled(DefaultUnleash.java:85)
	at no.finn.unleash.DefaultUnleash.isEnabled(DefaultUnleash.java:78)
	at no.finn.unleash.DefaultUnleash.isEnabled(DefaultUnleash.java:73)

**Comment by ivarconr** [comment]
which version of the client are you using? 
(We fixed a currency issue at some point)

**Comment by vkatoch2000** [comment]
3.2.3

**Comment by ivarconr** [comment]
Then you need to upgrade to 3.3.3, I think this will be solved by previous fixes.
