### ISSUE TITLE
Could not post to Unleash API - question

### ISSUE THREAD

**Issue by ulisses79** [Unleash/unleash-client-java#111]
I use version 3.3.3 with the custom authentication mechanism. There's a custom header provider etc.
From time to time I can see in logs: 'Could not post to Unleash API' with the stacktrace at the end of this message.

I assume that metrics are reported often and this error doesn't cause any significant issue for my client?
I can see it two times within 4 hours but sometimes it happens more often.

> java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:292) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
	at no.finn.unleash.metric.UnleashMetricsSender.post(UnleashMetricsSender.java:105)

**Comment by ivarconr** [comment]
Thanks for reporting. In general you only loose metrics, no other consequences. Other clients will actually keep metrics and resend them on next cycle, we should add this to the java sdk as well. 

Can you see anything in the Unleash-server logs? And which version of the server are you using?

**Comment by ulisses79** [comment]
Hi, The server version is Unleash 3.4.0
Java client version is 3.3.3.
I will ask for the server logs. I don't have access to it.
Recently it has happened 357 times within 1.5h - Datadog graph below:
![image](https://user-images.githubusercontent.com/9321546/89275646-d2bcde00-d642-11ea-8fc5-db6837f00fca.png)

**Comment by ulisses79** [comment]
In logs I can only see the repeating message like the lines below:

2020-08-11T13:44:34Z service/web/web-79c5cd8d85-ctwv4   "level": "info",
2020-08-11T13:45:34Z service/web/web-79c5cd8d85-ctwv4 }
2020-08-11T13:45:34Z service/web/web-79c5cd8d85-ctwv4 {
2020-08-11T13:45:34Z service/web/web-79c5cd8d85-ctwv4   "level": "info",
2020-08-11T13:45:34Z service/web/web-79c5cd8d85-ctwv4   "message": "Deleted 4 metrics"
2020-08-11T13:46:34Z service/web/web-79c5cd8d85-ctwv4 {
2020-08-11T13:46:34Z service/web/web-79c5cd8d85-ctwv4   "level": "info",
2020-08-11T13:46:34Z service/web/web-79c5cd8d85-ctwv4   "message": "Deleted 4 metrics"
2020-08-11T13:46:34Z service/web/web-79c5cd8d85-ctwv4 }
2020-08-11T13:47:34Z service/web/web-79c5cd8d85-ctwv4 {
2020-08-11T13:47:34Z service/web/web-79c5cd8d85-ctwv4   "level": "info",
2020-08-11T13:47:34Z service/web/web-79c5cd8d85-ctwv4   "message": "Deleted 4 metrics"
2020-08-11T13:47:34Z service/web/web-79c5cd8d85-ctwv4 }
2020-08-11T13:48:34Z service/web/web-79c5cd8d85-ctwv4 {
2020-08-11T13:48:34Z service/web/web-79c5cd8d85-ctwv4   "level": "info",
2020-08-11T13:48:34Z service/web/web-79c5cd8d85-ctwv4   "message": "Deleted 4 metrics"
2020-08-11T13:48:34Z service/web/web-79c5cd8d85-ctwv4 }
2020-08-11T13:49:34Z service/web/web-79c5cd8d85-ctwv4 {
2020-08-11T13:49:34Z service/web/web-79c5cd8d85-ctwv4   "level": "info",
2020-08-11T13:49:34Z service/web/web-79c5cd8d85-ctwv4   "message": "Deleted 4 metrics"
2020-08-11T13:49:34Z service/web/web-79c5cd8d85-ctwv4 }
2020-08-11T13:50:34Z service/web/web-79c5cd8d85-ctwv4 {
2020-08-11T13:50:34Z service/web/web-79c5cd8d85-ctwv4   "level": "info",
2020-08-11T13:50:34Z service/web/web-79c5cd8d85-ctwv4   "message": "Deleted 4 metrics"

**Comment by ivarconr** [comment]
to me the server looks happy and does not restart or complain on invalid data.

Thus; there might be something in the network that makes it timeout.

**Comment by jogaco** [comment]
I can see something similar. How often does the client post these metrics?

**Comment by ivarconr** [comment]
Hi @jogaco, If not configured otherwise [the default is 60s](https://github.com/Unleash/unleash-client-java/blob/master/src/main/java/no/finn/unleash/util/UnleashConfig.java#L214). 

Would be good to get to the bottom of this. It might be that we need the client to do retries before failing.

**Comment by jogaco** [comment]
Yep. Do one or two retries would be good. Maybe exposing http client config params too?

**Comment by jogaco** [comment]
Would make sense to improve the log, to rule out endpoint missconfigs?
`no.finn.unleash.UnleashException: Could not post to Unleash API at http://myfeaturetoggle-service`

**Comment by ivarconr** [comment]
yes, PR welcome =)
