### ISSUE TITLE
Proxy authentication not working

### ISSUE THREAD

**Issue by william00179** [Unleash/unleash-client-java#237]
### Describe the bug

Configuring Unleash to use a proxy with authentication. 

Unauthenticated proxy works well, but when you configure Unleash with credentials, the CustomProxyAuthenticator is created as expected in the configuration builder, but the `getPasswordAuthentication` method is never called and the requests to the proxy server fail with `HTTP/1.1 407 Proxy Authentication Required`

### Steps to reproduce the bug

1. Configure unleash with an authenticated HTTP proxy. 
2. Run unleash.

### Expected behavior

Unleash should provide the expected authentication

### Logs, error output, etc.

```bash
Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
gateway-qa-1  |         at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling0(HttpURLConnection.java:2271) ~[na:na]
gateway-qa-1  |         at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2143) ~[na:na]
gateway-qa-1  |         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:na]
gateway-qa-1  |         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:141) ~[na:na]
gateway-qa-1  |         at io.getunleash.repository.HttpFeatureFetcher.fetchFeatures(HttpFeatureFetcher.java:36) ~[unleash-client-java-9.2.0.jar!/:9.2.0]
gateway-qa-1  |         ... 52 common frames omitted
```

### Subscription type

None

### Hosting type

None

### SDK information (language and version)

9.2.0

**Comment by william00179** [comment]
It looks like this is an issue with the default fetcher if not using OkHttp. 

Java 8 removed the ability to use authenticated proxies with HttpURLConnection and HTTPS requests by default.

I will use my own feature fetcher with an HTTP client that supports the authenticated proxy.
