### ISSUE TITLE
getting error while using unleash client while running web app cygwin

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash-client-java#66]
```
2019-02-07 12:59:51.570  WARN 5092 --- [sh-api-executor] n.f.u.r.FeatureToggleRepository          : Could not refresh feature toggles
no.finn.unleash.UnleashException: Could not fetch toggles
        at no.finn.unleash.repository.HttpToggleFetcher.fetchToggles(HttpToggleFetcher.java:48)
        at no.finn.unleash.repository.FeatureToggleRepository.lambda$updateToggles$0(FeatureToggleRepository.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at no.finn.unleash.repository.HttpToggleFetcher.fetchToggles(HttpToggleFetcher.java:37)
        ... 8 common frames omitted
```

When we run web application in cygwin , has windows OS , its creating incorrect windows path with wrong slash using java client SDK

its throwing while creating repo file with  /cygwin/ C/x/ff.json , this slash will not work in cygwin

**Comment by vkatoch2000** [comment]
UnleashConfig unleashConfig = UnleashConfig.builder()
            .appName("XYZ")
            .instanceId(UUID.randomUUID().toString())
            .fetchTogglesInterval(60)
            .disableMetrics()
            .unleashAPI((com.wirelesscar.submgn.service.notification.Environment.isDevelopment() ?"http":"https")+"://localhost:"+env.getProperty("server.port")+"/api").build();

**Comment by ivarconr** [comment]
I'm sorry that you having difficulties using the client. The `no.finn.unleash.UnleashException: Could not fetch toggles` is thrown if it is not able to connect to the unleash API. I must admit I have little experience with Windows / Cygwin and all the quirks that might come of this. 

1. Would you mind providing the output of `System.out.println(unleashConfig.getUnleashAPI());`

2. It might be that the way we generate the URIs internally is not supported on windows, see [UnleashURLs.java#](https://github.com/Unleash/unleash-client-java/blob/master/src/main/java/no/finn/unleash/util/UnleashURLs.java#L15). Could you pleas run the following, and :

```java
URI apiURI = unleashConfig.getUnleashAPI();
        URL fetchTogglesURL = URI.create(apiURI + "/client/features").normalize().toURL();

System.out.println(fetchTogglesURL);

```


> its throwing while creating repo file with /cygwin/ C/x/ff.json , this slash will not work in cygwin

You should be able to specify a different backup file via the `backupFile` option. Can you please try specifying the backup-file to a valid file and see if this helps?

**Comment by vkatoch2000** [comment]
is there any way to disbale warn logs for client

**Comment by ivarconr** [comment]
> is there any way to disbale warn logs for client

yes. This you would configure via log4j2. By simply requiring level error or higher. e.g. in your `log4j2.xml` file:

```
<Logger name="no.finn.unleash" level="error" additivity="false">
    <AppenderRef ref="STDOUT" />
</Logger>
```
